embercsi/ember-csi-operator

deploy/olm-catalog/configmap.yml
Add openshift-operator-lifecycle-manager to the OLM configmap
and rearrange owned CRDs keys like it written in other configmaps
Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>
=> Add namespace to the configmap's metadata

README.md
Fixed a typo in README.md:
s/enber-csi/ember-csi
Change-Id: Iba530a32f022c3820fb4326df8f397a59a27832e
Signed-off-by: Daniel Erez <derez@redhat.com>
=> readme: fix typo in ember-csi

.dockerignore, Makefile, build/Dockerfile
This will resolve issue #9.
Note: multi-stage builds are a new feature requiring Docker 17.05 or
higher on the daemon and client.
=> Build binary in Docker

build/config.yml
Images from registry.redhat.io are only available with a Red Hat login,
thus using public images from quay.io for upstream releases.
=> Use public images from quay.io

pkg/controller/embercsi/embercsi_controller.go
Adds CRD as the default persistence config for Ember CSI if nothing is specified in the CR.
Close #13
=> Make CRD as default persistence for Ember CSI if nothing is specified

README.md
from-file should be 'system-files.tar' to correlate
with the 'spec.config.sysfiles.key' in the CR file example
('deploy/examples/external-ceph-cr.yaml').
Signed-off-by: Daniel Erez <derez@redhat.com>
=> README: fix secret creation example

pkg/controller/embercsi/embercsi_controller.go
Adds /var/lib/iscsi mount between host and pods. /run/udev already existed in the code.
Closes #16
=> Add /var/lib/iscsi mount

.gitignore
We should not store build artifacts in the repository - this increases
the repo size over time to unusable sizes, because all of them are
stored in the git history.
=> Remove build/_output

build/config.yaml, deploy/02-operator.yaml
Add/update sections for k8s-1.11 and k8s-1.13 sidecar image versions
based on https://kubernetes-csi.github.io/docs/sidecar-containers.html
Also changes the example deployment to use the default sidecar images
that are used for CSI spec v0.3.
=> Update config.yaml and set default to CSI spec v0.3

pkg/controller/embercsi/config.go
Checks if the named cluster name does exist in the provided config file
and falls back to "default" if not. Also removes the hardcoded default
config, which now must exist in config.yaml. Abort if no matching
cluster section is found.
=> Fail if cluster section does not exist

build/config.yaml
When using v1.2.0 it fails mounting volumes due to a wrong path used. v1.1.0 works fine with k8s-1.14.
=> Fix default external-provisioner version

deploy/examples/drivers/3par.yaml, deploy/examples/drivers/ceph-with-topology.yaml, deploy/examples/drivers/ceph.yaml, deploy/examples/drivers/kaminario.yaml, deploy/examples/drivers/lvm.yaml, deploy/examples/drivers/qnap.yaml, deploy/examples/drivers/solidfire.yaml, deploy/examples/drivers/synology.yaml, deploy/examples/drivers/vmax.yaml, deploy/examples/drivers/xtremio-fc.yaml, deploy/examples/drivers/xtremio-iscsi.yaml, pkg/controller/embercsi/common.go
These two changes will fix the defaults when using an OCP 4.x cluster.
It is possible to use OCP 4.x using slightly modified deployment .yamls, however this should be the default to make it easier for our users.
=> Bugfixes for OCP 4.x defaults

Gopkg.lock, Gopkg.toml, build/config.yaml, deploy/role.yaml, pkg/controller/embercsi/controller.go, pkg/controller/embercsi/embercsi_controller.go
The cluster-driver-registrar is deprecated and the CSIDriver needs
to be created by the deployment itself. The CSIDriver object will
be only created if there is no cluster registrar sidecar defined
to keep compatibility with older cluster versions.
See https://kubernetes-csi.github.io/docs/csi-driver-object.html
and https://github.com/kubernetes-csi/cluster-driver-registrar
for further details.
This also updates the SDK requirements to 1.14.
Closes embercsi/ember-csi-operator#90
=> Add CSIDriver object

.gitignore, build/olm-catalog/olm-csv-gen.sh, build/olm-catalog/template-dev.yaml, build/olm-catalog/template.yaml, build/olm-catalog/yaml-options-gen.py, deploy/olm-catalog/next/ember-csi-operator.vX.Y.Z.clusterserviceversion.yaml
There are too many drivers to add configuration options manually, so we leverage the Ember-CSI script that outputs detailed information about drivers to automatically generate the form fields and examples on the OLM catalog.
The new script olvm-csv-gen.sh runs an Ember-CSI docker container to get the driver specific configuration options and the passes them to a Python script to generate the Cluster Service Version YAML file `deploy/olm-catalog/next/ember-csi-operator.vX.Y.Z.clusterserviceversion.yaml`
In this file we'll have:
- One example with all the configuration options for all the drivers (this is used for default values).
- One example for each driver which its own configuration options.
- The form options.
The Python script has the capability to ignore some drivers (like the NFS …
=> Add script to generate form config options

build/config.yaml
Add newer OpenShift and Kubernetes releases to the config.yaml file and
also add a future release so it doesn't default to CSI v1.0 if we use
the operator on them before we have time to update the file.
=> Update container's config.yaml

pkg/controller/embercsi/common.go, pkg/controller/embercsi/common_test.go
Make sure an empty string is transformed into an empty list,
not a list with a single 0-byte sized string.
=> Fix transform_csv on empty strings

build/config.yaml
Update the csi-snapshotter container tag to v2.1.3 to fix CVE-2020-8569:
https://github.com/kubernetes-csi/external-snapshotter/issues/421
=> CVE-2020-8569: Update snapshotter sidecar

build/olm-catalog/olm-csv-gen.sh, build/olm-catalog/yaml-options-gen.py, deploy/olm-catalog/next/ember-csi-operator.vX.Y.Z.clusterserviceversion.yaml
The iSCSI and FC Cinder driver for HPE MSA is not reporting all the
configuration options that the drivers require to run [1]
While the proposed fix [2] lands in Cinder and is released, we propose
this patch that manually adds the missing options to these 2 drivers.
[1]: https://docs.openstack.org/cinder/latest/configuration/block-storage/drivers/hp-msa-driver.html
[2]: https://review.opendev.org/c/openstack/cinder/+/770807
=> Add missing HPE MSA config options to the form

build/olm-catalog/olm-csv-gen.sh, build/olm-catalog/yaml-options-gen.py
This PR updates our form auto-generating script to:
- Specifically pull the ember-csi image from quay.io
- Only use `podman`
- Disable `enforce_multipath_for_image_xfer` config option
- Remove driver specific `enable_unsupported_driver` option that gets overwritten with the global one.
=> Tweak the old-csv-gen.sh script

pkg/controller/embercsi/node.go
Removes the secret (which includes X_CSI_BACKEND_CONFIG)
from the node environment.
=> Remove backend config env from nodes

deploy/olm-catalog/0.9.6/ember-csi-operator.crd.yaml, deploy/olm-catalog/0.9.6/ember-csi-operator.v0.9.6.clusterserviceversion.yaml, deploy/olm-catalog/ember-csi-operator.package.yaml
Fixes the multipath envVars setting and
version errors in the 0.9.5 catalog entry.
=> Catalog update to 0.9.6

build/config.yaml
This patch updates the build/config.yaml file to add required sidecar
container images for ocp 4.7, 4.8, and 4.9 versions as well as k8s
1.21 and 1.22.
Some time ago we changed images from docker hub to quay.io because of
the limiting, but now there's also images in Google's registry
(k8s.gcr.io) and they are more up to date than quay, so the patch also
updates some of the sidecar images for older releases.
=> Support newer k8s & ocp versions
